CPP=g++ -std=c++11
CPPFLAGS=-O3 -Wall -DVERBOSE
INCLUDES=-I./include/
SOURCES=./include/BasicCDS.cpp readWriteIntegers.cpp

unary:
	@echo " [BLD] Building binary unary"
	@$(CPP) $(CPPFLAGS) $(INCLUDES) $(SOURCES) -o readWriteInt
